import Moore57.D19OnMoore57.AFiber.CoordinateOrbit
import Moore57.D19OnMoore57.AFiber.OrbitBaseSelection

/-!
# Orbit-base selections from moved-branch A-fiber coordinates

This file specializes the generic A-fiber orbit-base selection bridge to the
common constructor `AFiberCoordinates.ofRotationOrbitOfMoved`.
-/

namespace Moore57

variable {V : Type*} [Fintype V] [DecidableEq V]
variable {Γ : SimpleGraph V} [DecidableRel Γ.Adj]

namespace AFiberCoordinates

/-- The orbit-base selection generated by the A-fiber coordinates of a moved
branch rotation orbit. -/
noncomputable def ofRotationOrbitOfMoved_toOrbitBaseSelectionInput
    (h : D19ActsOnMoore57 V Γ) (u a0 : V)
    (hu : ∀ d : ZMod 19, h.rotation d u = u)
    (hub0 : Γ.Adj u a0)
    {d : ZMod 19} (hd : d ≠ 0) (hmove : h.rotation d a0 ≠ a0) :
    OrbitBaseSelectionInput h :=
  (ofRotationOrbitOfMoved h u a0 hu hub0 hd hmove)
    |>.toOrbitBaseSelectionInputOfMoore
      (ofRotationOrbitOfMoved_rotationEquivariance
        h u a0 hu hub0 hd hmove)

/-- The canonical carrier witness generated by the A-fiber coordinates of a
moved branch rotation orbit. -/
noncomputable def ofRotationOrbitOfMoved_toCanonicalCarrierWitness
    (h : D19ActsOnMoore57 V Γ) (u a0 : V)
    (hu : ∀ d : ZMod 19, h.rotation d u = u)
    (hub0 : Γ.Adj u a0)
    {d : ZMod 19} (hd : d ≠ 0) (hmove : h.rotation d a0 ≠ a0) :
    OrbitBaseSelectionCanonicalCarrierWitness h :=
  (ofRotationOrbitOfMoved h u a0 hu hub0 hd hmove)
    |>.toCanonicalCarrierWitnessOfMoore
      (ofRotationOrbitOfMoved_rotationEquivariance
        h u a0 hu hub0 hd hmove)

end AFiberCoordinates

end Moore57
