import Moore57.Moore57Graph.AFiber.FiberUnionCardinality
import Moore57.D19OnMoore57.AFiber.OrbitMoved
import Moore57.D19OnMoore57.Orbit.BaseSelectionCanonicalCarrierCardinality
import Moore57.D19OnMoore57.Orbit.BaseSelectionEnumeration

/-!
# Orbit-base selections from equivariant A-fiber coordinates

An equivariant A-fiber coordinate system contains `56` coordinate points in
the base fiber.  Once these points are identified with `Fin 56`, their
rotation orbits give the standard base-selection input used by the final
counting pipeline.
-/

namespace Moore57

universe u uP

variable {V : Type u} [Fintype V] [DecidableEq V]
variable {Γ : SimpleGraph V} [DecidableRel Γ.Adj]

namespace AFiberCoordinates

variable {h : D19ActsOnMoore57 V Γ}
variable {coords : AFiberCoordinates.{u, uP} Γ}

/-- The canonical finite equivalence obtained from the Moore57 cardinality of
the base A-fiber coordinate type. -/
noncomputable def fin56EquivOfMoore
    (hΓ : IsMoore57 Γ) : Fin 56 ≃ coords.P := by
  letI := coords.P_fintype
  exact (Fintype.equivFinOfCardEq (coords.card_P hΓ)).symm

/-- The base vertex in the A-fiber orbit corresponding to a coordinate point
of the base fiber. -/
noncomputable def orbitBaseFromEquiv
    (e : Fin 56 ≃ coords.P) (q : Fin 56) : V :=
  ((coords.coord 0 (e q) :
    {x : V // x ∈ branchFiber Γ coords.u (coords.a 0)}) : V)

/-- The explicit coordinate enumeration of the rotation orbits coming from an
equivariant A-fiber coordinate system. -/
noncomputable def orbitSelectionCoord
    (rot : AFiberRotationEquivariance h coords)
    (e : Fin 56 ≃ coords.P) (qi : Fin 56 × ZMod 19) : V :=
  ((coords.coord (0 + qi.2) (rot.coordPerm qi.2 0 (e qi.1)) :
    {x : V // x ∈ branchFiber Γ coords.u (coords.a (0 + qi.2))}) : V)

/-- The A-fiber coordinate enumeration agrees with the rotation-coordinate
map generated by the base fiber. -/
theorem orbitSelectionCoord_eq_rotation
    (rot : AFiberRotationEquivariance h coords)
    (e : Fin 56 ≃ coords.P) (qi : Fin 56 × ZMod 19) :
    coords.orbitSelectionCoord rot e qi =
      h.rotation qi.2 (coords.orbitBaseFromEquiv e qi.1) := by
  cases qi with
  | mk q i =>
      change
        ((coords.coord (0 + i) (rot.coordPerm i 0 (e q)) :
          {x : V // x ∈ branchFiber Γ coords.u (coords.a (0 + i))}) : V) =
          h.rotation i
            (((coords.coord 0 (e q) :
              {x : V // x ∈ branchFiber Γ coords.u (coords.a 0)}) : V))
      exact rot.coord_coordPerm_apply_val i 0 (e q)

/-- The A-fiber coordinate enumeration has no repeated vertices. -/
theorem orbitSelectionCoord_injective
    (rot : AFiberRotationEquivariance h coords)
    (e : Fin 56 ≃ coords.P) :
    Function.Injective (coords.orbitSelectionCoord rot e) := by
  intro qi rj hcoord
  rcases qi with ⟨q, i⟩
  rcases rj with ⟨r, j⟩
  have hrot :
      h.rotation i (coords.orbitBaseFromEquiv e q) =
        h.rotation j (coords.orbitBaseFromEquiv e r) := by
    calc
      h.rotation i (coords.orbitBaseFromEquiv e q)
          = coords.orbitSelectionCoord rot e ((q, i) : Fin 56 × ZMod 19) :=
            (coords.orbitSelectionCoord_eq_rotation rot e
              ((q, i) : Fin 56 × ZMod 19)).symm
      _ = coords.orbitSelectionCoord rot e ((r, j) : Fin 56 × ZMod 19) :=
            hcoord
      _ = h.rotation j (coords.orbitBaseFromEquiv e r) :=
            coords.orbitSelectionCoord_eq_rotation rot e
              ((r, j) : Fin 56 × ZMod 19)
  by_cases hij : i = j
  · subst j
    have hbase :
        coords.orbitBaseFromEquiv e q = coords.orbitBaseFromEquiv e r :=
      (h.rotation i).injective hrot
    have hsub :
        coords.coord 0 (e q) = coords.coord 0 (e r) := by
      apply Subtype.ext
      exact hbase
    have he : e q = e r := (coords.coord 0).injective hsub
    exact Prod.ext (e.injective he) rfl
  · have hi_mem :
        h.rotation i (coords.orbitBaseFromEquiv e q) ∈
          branchFiber Γ coords.u (coords.a (0 + i)) := by
      simpa [orbitBaseFromEquiv] using
        (rot.rotation_coord_mem_fiber i 0 (e q))
    have hj_mem_right :
        h.rotation j (coords.orbitBaseFromEquiv e r) ∈
          branchFiber Γ coords.u (coords.a (0 + j)) := by
      simpa [orbitBaseFromEquiv] using
        (rot.rotation_coord_mem_fiber j 0 (e r))
    have hj_mem :
        h.rotation i (coords.orbitBaseFromEquiv e q) ∈
          branchFiber Γ coords.u (coords.a (0 + j)) := by
      rw [hrot]
      exact hj_mem_right
    have hindex : (0 : ZMod 19) + i ≠ 0 + j := by
      intro hzero
      exact hij (by simpa using hzero)
    have hdisj :
        Disjoint (branchFiber Γ coords.u (coords.a (0 + i)))
          (branchFiber Γ coords.u (coords.a (0 + j))) :=
      h.isMoore.branchFiber_disjoint_of_ne
        (coords.hub (0 + i)) (coords.hub (0 + j))
        (coords.a_ne hindex)
    exact False.elim (Finset.disjoint_left.mp hdisj hi_mem hj_mem)

/-- A rotation-equivariant A-fiber coordinate system, together with an
enumeration of its base-fiber coordinates by `Fin 56`, yields a coordinate
enumeration of the selected rotation orbits. -/
noncomputable def toOrbitBaseSelectionEnumeration
    (rot : AFiberRotationEquivariance h coords)
    (e : Fin 56 ≃ coords.P) :
    OrbitBaseSelectionEnumeration h where
  base := coords.orbitBaseFromEquiv e
  coord := coords.orbitSelectionCoord rot e
  coord_eq_rotation :=
    coords.orbitSelectionCoord_eq_rotation rot e
  coord_injective :=
    coords.orbitSelectionCoord_injective rot e

/-- A rotation-equivariant A-fiber coordinate system, together with an
enumeration of its base-fiber coordinates by `Fin 56`, yields the downstream
orbit-base selection input. -/
noncomputable def toOrbitBaseSelectionInput
    (rot : AFiberRotationEquivariance h coords)
    (e : Fin 56 ≃ coords.P) :
    OrbitBaseSelectionInput h :=
  (coords.toOrbitBaseSelectionEnumeration rot e).toInput

/-- Version of `toOrbitBaseSelectionEnumeration` using the Moore57 cardinality
of the A-fiber coordinate type to choose the `Fin 56` enumeration
automatically. -/
noncomputable def toOrbitBaseSelectionEnumerationOfMoore
    (rot : AFiberRotationEquivariance h coords) :
    OrbitBaseSelectionEnumeration h :=
  coords.toOrbitBaseSelectionEnumeration rot
    (coords.fin56EquivOfMoore h.isMoore)

/-- Version of `toOrbitBaseSelectionInput` using the Moore57 cardinality of
the A-fiber coordinate type to choose the `Fin 56` enumeration automatically.
-/
noncomputable def toOrbitBaseSelectionInputOfMoore
    (rot : AFiberRotationEquivariance h coords) :
    OrbitBaseSelectionInput h :=
  (coords.toOrbitBaseSelectionEnumerationOfMoore rot).toInput

/-- The canonical carrier witness generated by the selected A-fiber coordinate
orbits. -/
noncomputable def toCanonicalCarrierWitnessOfMoore
    (rot : AFiberRotationEquivariance h coords) :
    OrbitBaseSelectionCanonicalCarrierWitness h :=
  (coords.toOrbitBaseSelectionEnumerationOfMoore rot).toCanonicalCarrierWitness

end AFiberCoordinates

end Moore57
