import Moore57.OrbitBaseSelectionCarrierSimp

/-!
# Canonical carrier witnesses for orbit-base selections

This file packages the special case where the carrier finset is exactly the
canonical orbit-family union `h.orbitFamilyUnion base`.
-/

namespace Moore57

variable {V : Type*} [Fintype V] [DecidableEq V]
variable {Γ : SimpleGraph V} [DecidableRel Γ.Adj]

/-- A carrier witness whose carrier is definitionally the canonical
orbit-family union generated by the selected bases. -/
structure OrbitBaseSelectionCanonicalCarrierWitness
    (h : D19ActsOnMoore57 V Γ) where
  /-- One representative for each of the 56 rotation orbits. -/
  base : Fin 56 → V
  /-- The canonical orbit-family union has the expected bounded size. -/
  orbitFamilyUnion_card : (h.orbitFamilyUnion base).card = 1064

namespace OrbitBaseSelectionCanonicalCarrierWitness

variable {h : D19ActsOnMoore57 V Γ}

/-- Convert a canonical carrier witness to the general carrier-witness API. -/
noncomputable def toCarrierWitness
    (w : OrbitBaseSelectionCanonicalCarrierWitness h) :
    OrbitBaseSelectionCarrierWitness h where
  base := w.base
  carrier := h.orbitFamilyUnion w.base
  mem_carrier := h.mem_orbitFamilyUnion w.base
  carrier_card := w.orbitFamilyUnion_card

@[simp] theorem toCarrierWitness_base
    (w : OrbitBaseSelectionCanonicalCarrierWitness h) :
    w.toCarrierWitness.base = w.base := by
  rfl

@[simp] theorem toCarrierWitness_base_apply
    (w : OrbitBaseSelectionCanonicalCarrierWitness h) (q : Fin 56) :
    w.toCarrierWitness.base q = w.base q := by
  rfl

@[simp] theorem toCarrierWitness_carrier
    (w : OrbitBaseSelectionCanonicalCarrierWitness h) :
    w.toCarrierWitness.carrier = h.orbitFamilyUnion w.base := by
  rfl

@[simp] theorem mem_toCarrierWitness_carrier
    (w : OrbitBaseSelectionCanonicalCarrierWitness h) (y : V) :
    y ∈ w.toCarrierWitness.carrier ↔
      ∃ q : Fin 56, ∃ i : ZMod 19, h.rotation i (w.base q) = y := by
  simpa using h.mem_orbitFamilyUnion w.base y

@[simp] theorem toCarrierWitness_orbitFamilyUnion_card
    (w : OrbitBaseSelectionCanonicalCarrierWitness h) :
    (h.orbitFamilyUnion w.toCarrierWitness.base).card = 1064 := by
  simpa using w.orbitFamilyUnion_card

end OrbitBaseSelectionCanonicalCarrierWitness

end Moore57
