name = "Moore57"
version = "0.1.0"
defaultTargets = ["Moore57"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.1"

[[lean_lib]]
name = "Moore57"

[[lean_exe]]
name = "lintText"
srcDir = "scripts"
supportInterpreter = true
