import Moore57.D19OnMoore57.BranchOrbit.ABCResidualBridge
import Moore57.D19OnMoore57.BranchOrbit.ABCFromCenter

/-!
# Geometry behind branch-orbit residual classification

This file isolates the geometric part of the residual-classification
assumption used by `BranchOrbitABCResidualBridge`.  The current bridge asks
directly that every non-fixed residual vertex lies in the A-fibers.  The lemmas
below reduce that to two more geometric facts: such a vertex is not adjacent to
the center, and the unique branch fiber containing it is an A-branch orbit.
-/

namespace Moore57

open Finset

noncomputable section

universe u uP

variable {V : Type u} [Fintype V] [DecidableEq V]
variable {Γ : SimpleGraph V} [DecidableRel Γ.Adj]

namespace AFiberCoordinates

variable (coords : AFiberCoordinates.{u, uP} Γ)

/-- A vertex in a selected A-fiber union is not adjacent to the center. -/
theorem not_adj_center_of_mem_fiberUnion
    (hΓ : IsMoore57 Γ) {indices : Finset (ZMod 19)} {y : V}
    (hy : y ∈ coords.fiberUnion indices) :
    ¬ Γ.Adj coords.u y := by
  rcases (coords.mem_fiberUnion_iff indices y).mp hy with
    ⟨i, _hi, hyi⟩
  exact hΓ.not_adj_center_of_mem_branchFiber (coords.hub i) hyi

/-- A vertex in the union of all A-fibers is not adjacent to the center. -/
theorem not_adj_center_of_mem_allFibers
    (hΓ : IsMoore57 Γ) {y : V}
    (hy : y ∈ coords.allFibers) :
    ¬ Γ.Adj coords.u y := by
  exact coords.not_adj_center_of_mem_fiberUnion hΓ
    (indices := Finset.univ) hy

end AFiberCoordinates

namespace BranchOrbitABCData

variable {h : D19ActsOnMoore57 V Γ}

/-- The center stored in `BranchOrbitABCData` is the canonical rotation-fixed
center. -/
theorem u_eq_rotationFixedCenter
    (data : BranchOrbitABCData h) :
    data.u = h.rotationFixedCenter :=
  h.eq_rotationFixedCenter_of_rotation_one_fixed (data.u_fixed 1)

/-- A vertex outside the rotation-one fixed set is not the stored center. -/
theorem ne_u_of_not_mem_fixedVertexSet
    (data : BranchOrbitABCData h) {y : V}
    (hy : y ∉ fixedVertexSet (h.rotation 1)) :
    data.u ≠ y := by
  intro huy
  exact hy (mem_fixedVertexSet.mpr (by
    rw [← huy]
    exact data.u_fixed 1))

/-- Membership in the A-fibers generated by `BranchOrbitABCData`, expanded to
the corresponding A-branch rotation orbit. -/
theorem mem_toAFiberCoordinates_allFibers_iff
    (data : BranchOrbitABCData h) (y : V) :
    y ∈ data.toAFiberCoordinates.allFibers ↔
      ∃ i : ZMod 19,
        y ∈ branchFiber Γ data.u (h.rotation i data.a0) := by
  simpa [BranchOrbitABCData.toAFiberCoordinates] using
    data.toAFiberCoordinates.mem_allFibers_iff y

/-- If the branch fiber containing a vertex lies over an A-branch orbit, then
the vertex lies in the generated A-fibers. -/
theorem mem_allFibers_of_mem_branchFiber_aOrbit
    (data : BranchOrbitABCData h) {b y : V}
    (hb : b ∈ h.rotationOrbitFinset data.a0)
    (hy : y ∈ branchFiber Γ data.u b) :
    y ∈ data.toAFiberCoordinates.allFibers := by
  rcases (h.mem_rotationOrbitFinset data.a0 b).mp hb with ⟨i, hi⟩
  rw [data.mem_toAFiberCoordinates_allFibers_iff]
  exact ⟨i, by simpa [hi] using hy⟩

/-- A direct residual-classification assumption forces non-fixed residual
vertices to be non-neighbors of the A-fiber center.  This records a necessary
condition for proving the classification from geometry. -/
theorem nonfixed_residual_not_adj_center_of_nonfixed_residual_subset
    (data : BranchOrbitABCData h) (k : ZMod 19)
    (hnonfixed :
      ∀ ⦃y : V⦄,
        y ∈ reflectionCopyResidual h data.toOrbitBaseSelectionInput.base k →
          y ∉ fixedVertexSet (h.rotation 1) →
            y ∈ data.toAFiberCoordinates.allFibers) :
    ∀ ⦃y : V⦄,
      y ∈ reflectionCopyResidual h data.toOrbitBaseSelectionInput.base k →
        y ∉ fixedVertexSet (h.rotation 1) →
          ¬ Γ.Adj data.u y := by
  intro y hyResidual hyNonfixed
  exact data.toAFiberCoordinates.not_adj_center_of_mem_allFibers
    h.isMoore (hnonfixed hyResidual hyNonfixed)

/-- Reduce the residual-classification assumption to two geometric facts:
non-fixed residual vertices are not center-neighbors, and their unique branch
fiber lies over the A-branch orbit. -/
theorem nonfixed_residual_subset_allFibers_of_not_adj_center_and_branch_mem_aOrbit
    (data : BranchOrbitABCData h) (k : ZMod 19)
    (hnotAdjCenter :
      ∀ ⦃y : V⦄,
        y ∈ reflectionCopyResidual h data.toOrbitBaseSelectionInput.base k →
          y ∉ fixedVertexSet (h.rotation 1) →
            ¬ Γ.Adj data.u y)
    (hbranchA :
      ∀ ⦃y b : V⦄,
        y ∈ reflectionCopyResidual h data.toOrbitBaseSelectionInput.base k →
          y ∉ fixedVertexSet (h.rotation 1) →
            Γ.Adj data.u b →
              y ∈ branchFiber Γ data.u b →
                b ∈ h.rotationOrbitFinset data.a0) :
    ∀ ⦃y : V⦄,
      y ∈ reflectionCopyResidual h data.toOrbitBaseSelectionInput.base k →
        y ∉ fixedVertexSet (h.rotation 1) →
          y ∈ data.toAFiberCoordinates.allFibers := by
  intro y hyResidual hyNonfixed
  have hy_ne_u : data.u ≠ y := data.ne_u_of_not_mem_fixedVertexSet hyNonfixed
  rcases h.isMoore.existsUnique_branch_of_not_adj_center
      hy_ne_u (hnotAdjCenter hyResidual hyNonfixed) with
    ⟨b, hb, _huniq⟩
  exact data.mem_allFibers_of_mem_branchFiber_aOrbit
    (hbranchA hyResidual hyNonfixed hb.1 hb.2) hb.2

end BranchOrbitABCData

namespace BranchOrbitABCFromCenter

variable {h : D19ActsOnMoore57 V Γ}

/-- Membership in the A-fibers generated from center-neighbor data, expanded
to the corresponding A-branch rotation orbit. -/
theorem mem_toAFiberCoordinates_allFibers_iff
    (data : BranchOrbitABCFromCenter h) (y : V) :
    y ∈ data.toAFiberCoordinates.allFibers ↔
      ∃ i : ZMod 19,
        y ∈ branchFiber Γ data.u (h.rotation i data.a0) := by
  simpa [BranchOrbitABCFromCenter.toAFiberCoordinates] using
    data.toAFiberCoordinates.mem_allFibers_iff y

/-- Center-neighbor data covers every center-neighbor by one of the three
branch rotation orbits. -/
theorem neighbor_mem_a_or_b_or_c_orbit
    (data : BranchOrbitABCFromCenter h) {b : V}
    (hb : Γ.Adj data.u b) :
    b ∈ h.rotationOrbitFinset data.a0 ∨
      b ∈ h.rotationOrbitFinset data.b0 ∨
        b ∈ h.rotationOrbitFinset data.c0 := by
  have hbNeighbor : b ∈ Γ.neighborFinset data.u := by
    simpa [SimpleGraph.mem_neighborFinset] using hb
  have hbUnion : b ∈ h.orbitFamilyUnion data.base := by
    simpa [data.cover_neighbors] using hbNeighbor
  rcases (h.mem_orbitFamilyUnion data.base b).mp hbUnion with
    ⟨q, i, hi⟩
  have hbOrbit : b ∈ h.rotationOrbitFinset (data.base q) :=
    (h.mem_rotationOrbitFinset (data.base q) b).mpr ⟨i, hi⟩
  fin_cases q
  · exact Or.inl (by simpa using hbOrbit)
  · exact Or.inr (Or.inl (by simpa using hbOrbit))
  · exact Or.inr (Or.inr (by simpa using hbOrbit))

/-- If the branch fiber containing a vertex lies over an A-branch orbit, then
the vertex lies in the generated A-fibers. -/
theorem mem_allFibers_of_mem_branchFiber_aOrbit
    (data : BranchOrbitABCFromCenter h) {b y : V}
    (hb : b ∈ h.rotationOrbitFinset data.a0)
    (hy : y ∈ branchFiber Γ data.u b) :
    y ∈ data.toAFiberCoordinates.allFibers := by
  rcases (h.mem_rotationOrbitFinset data.a0 b).mp hb with ⟨i, hi⟩
  rw [data.mem_toAFiberCoordinates_allFibers_iff]
  exact ⟨i, by simpa [hi] using hy⟩

/-- Center-neighbor data proves A-fiber membership once the residual vertex is
known to be non-adjacent to the center and its unique branch is known to be in
the A-branch orbit. -/
theorem mem_allFibers_of_not_adj_center_and_branch_mem_aOrbit
    (data : BranchOrbitABCFromCenter h) {y : V}
    (hy_ne_u : data.u ≠ y)
    (hnotAdjCenter : ¬ Γ.Adj data.u y)
    (hbranchA :
      ∀ ⦃b : V⦄,
        Γ.Adj data.u b →
          y ∈ branchFiber Γ data.u b →
            b ∈ h.rotationOrbitFinset data.a0) :
    y ∈ data.toAFiberCoordinates.allFibers := by
  rcases h.isMoore.existsUnique_branch_of_not_adj_center
      hy_ne_u hnotAdjCenter with
    ⟨b, hb, _huniq⟩
  exact data.mem_allFibers_of_mem_branchFiber_aOrbit
    (hbranchA hb.1 hb.2) hb.2

end BranchOrbitABCFromCenter

end

end Moore57
