import Moore57.D19OnMoore57.BranchOrbit.BranchOrbitABCResidualSplit
import Moore57.D19OnMoore57.Misc.CenterNeighborContributionZero
import Moore57.D19OnMoore57.AFiber.AFiberCardinalityBoundary
import Moore57.D19OnMoore57.AdjacentMoved.AdjacentMovedReflectionCompactSplit

/-!
# Residual contribution for the B/C selected split

The canonical B-fiber selected residual is `centerNeighborPart ∪ A_fibers`.
The first summand contributes zero to the adjacent-moved count, and an
`AFiberCardinality38Boundary` supplies the `38` contribution from the A-side.
This packages the result in the generic compact split-residual witness.
-/

namespace Moore57

open Finset

noncomputable section

universe u

variable {V : Type u} [Fintype V] [DecidableEq V]
variable {Γ : SimpleGraph V} [DecidableRel Γ.Adj]

namespace D19ActsOnMoore57

variable (h : D19ActsOnMoore57 V Γ)

/-- The rotation orbit of a point in one branch fiber stays inside the branch
leaf generated by the corresponding center-neighbor orbit. -/
theorem rotationOrbitFinset_subset_branchOrbitLeaf_of_mem_branchFiber
    {u b x : V} (hu : ∀ d : ZMod 19, h.rotation d u = u)
    (hx : x ∈ branchFiber Γ u b) :
    h.rotationOrbitFinset x ⊆ h.branchOrbitLeaf u b := by
  intro y hy
  rcases (h.mem_rotationOrbitFinset x y).mp hy with ⟨i, hi⟩
  rw [h.mem_branchOrbitLeaf_iff]
  refine ⟨i, ?_⟩
  rw [← hi]
  exact (h.rotation_mem_branchFiber_iff i
    (u := u) (b := b) (x := x) (hu i)).2 hx

end D19ActsOnMoore57

namespace BranchOrbitABCFromCenter

variable {h : D19ActsOnMoore57 V Γ}

/-- The zero part `{u} ∪ N(u)` is disjoint from the A-side all-fiber union. -/
theorem zeroPart_disjoint_toAFiberCoordinates_allFibers
    (data : BranchOrbitABCFromCenter h) :
    Disjoint (centerNeighborPart Γ data.u) data.toAFiberCoordinates.allFibers := by
  rw [← data.aSideLeaf_eq_allFibers]
  exact h.centerNeighborPart_disjoint_branchOrbitLeaf
    data.u_fixed data.a0_adj

/-- The center-neighbor residual piece plus the A-side all-fiber piece has
constant adjacent-moved contribution `38`. -/
theorem zeroPart_union_allFibers_residual_contribution
    (data : BranchOrbitABCFromCenter h)
    (boundary :
      AFiberCardinality38Boundary h data.toAFiberCoordinates
        (Finset.univ : Finset (ZMod 19))) :
    ∀ d : ZMod 19, ∀ _hd : d ≠ 0,
      ((centerNeighborPart Γ data.u).filter fun y =>
          Γ.Adj y (h.rotation d y)).card +
        (data.toAFiberCoordinates.allFibers.filter fun y =>
          Γ.Adj y (h.rotation d y)).card =
        38 := by
  intro d hd
  have hzero :
      ((centerNeighborPart Γ data.u).filter fun y =>
          Γ.Adj y (h.rotation d y)).card = 0 :=
    h.centerNeighborPart_filter_adjacent_rotation_card_eq_zero
      data.u_fixed d
  have ha :
      (data.toAFiberCoordinates.allFibers.filter fun y =>
          Γ.Adj y (h.rotation d y)).card = 38 := by
    simpa [AFiberCoordinates.allFibers, fixedAFiberAFiberCard] using
      boundary.card_eq_thirtyEight d hd
  simp [hzero, ha]

/-- The B- and C-side branch leaves are disjoint. -/
theorem bSideLeaf_disjoint_cSideLeaf
    (data : BranchOrbitABCFromCenter h) :
    Disjoint data.bSideLeaf data.cSideLeaf := by
  exact h.branchOrbitLeaf_disjoint_of_rotationOrbitFinset_disjoint
    data.u_fixed data.b0_adj data.c0_adj
    (by simpa using data.pairwise_disjoint 1 2 (by decide))

/-- Each canonical B-fiber selected base orbit lies in the B-side leaf. -/
theorem rotationOrbitFinset_toOrbitBaseSelectionInputFromBFibers_base_subset_bSideLeaf
    (data : BranchOrbitABCFromCenter h) (q : Fin 56) :
    h.rotationOrbitFinset (data.toOrbitBaseSelectionInputFromBFibers.base q) ⊆
      data.bSideLeaf := by
  have hmem :
      data.toOrbitBaseSelectionInputFromBFibers.base q ∈
        branchFiber Γ data.u data.b0 := by
    rw [data.toOrbitBaseSelectionInputFromBFibers_base_eq_b0FiberBase]
    exact data.b0FiberBase_mem
      data.toBFiberCoordinatesBaseFiberEquiv q
  exact h.rotationOrbitFinset_subset_branchOrbitLeaf_of_mem_branchFiber
    data.u_fixed hmem

/-- Each reflected canonical B-fiber selected base orbit lies in the C-side
leaf when the reflection sends `b0` to `c0`. -/
theorem rotationOrbitFinset_reflection_toOrbitBaseSelectionInputFromBFibers_base_subset_cSideLeaf
    (data : BranchOrbitABCFromCenter h) {k : ZMod 19}
    (href : h.smul (DihedralGroup.sr k) data.b0 = data.c0)
    (q : Fin 56) :
    h.rotationOrbitFinset
        (h.smul (DihedralGroup.sr k)
          (data.toOrbitBaseSelectionInputFromBFibers.base q)) ⊆
      data.cSideLeaf := by
  have hmem :
      h.smul (DihedralGroup.sr k)
          (data.toOrbitBaseSelectionInputFromBFibers.base q) ∈
        branchFiber Γ data.u data.c0 := by
    rw [data.toOrbitBaseSelectionInputFromBFibers_base_eq_b0FiberBase]
    exact data.reflection_b0FiberBase_mem_c0Fiber
      data.toBFiberCoordinatesBaseFiberEquiv href q
  exact h.rotationOrbitFinset_subset_branchOrbitLeaf_of_mem_branchFiber
    data.u_fixed hmem

/-- Original B-fiber selected orbits and their reflected C-side copies are
pairwise disjoint. -/
theorem cross_disjoint_toOrbitBaseSelectionInputFromBFibers_of_reflection_smul_b0_eq_c0
    (data : BranchOrbitABCFromCenter h) {k : ZMod 19}
    (href : h.smul (DihedralGroup.sr k) data.b0 = data.c0) :
    ∀ q r : Fin 56,
      Disjoint
        (h.rotationOrbitFinset
          (data.toOrbitBaseSelectionInputFromBFibers.base q))
        (h.rotationOrbitFinset
          (h.smul (DihedralGroup.sr k)
            (data.toOrbitBaseSelectionInputFromBFibers.base r))) := by
  intro q r
  rw [Finset.disjoint_left]
  intro y hyB hyC
  exact (Finset.disjoint_left.mp data.bSideLeaf_disjoint_cSideLeaf)
    (data.rotationOrbitFinset_toOrbitBaseSelectionInputFromBFibers_base_subset_bSideLeaf
      q hyB)
    (data.rotationOrbitFinset_reflection_toOrbitBaseSelectionInputFromBFibers_base_subset_cSideLeaf
      href r hyC)

/-- Package the natural-language Section 7 residual split as the generic
compact split-residual witness for the canonical B-fiber selected input. -/
noncomputable def toComplementResidualSplit38WitnessFromBFibers
    (data : BranchOrbitABCFromCenter h)
    (boundary :
      AFiberCardinality38Boundary h data.toAFiberCoordinates
        (Finset.univ : Finset (ZMod 19)))
    {k : ZMod 19}
    (href : h.smul (DihedralGroup.sr k) data.b0 = data.c0)
    (cross_disjoint :
      ∀ q r : Fin 56,
        Disjoint
          (h.rotationOrbitFinset
            (data.toOrbitBaseSelectionInputFromBFibers.base q))
          (h.rotationOrbitFinset
            (h.smul (DihedralGroup.sr k)
              (data.toOrbitBaseSelectionInputFromBFibers.base r)))) :
    AdjacentMovedReflectionComplementResidualSplit38Witness h
      data.toOrbitBaseSelectionInputFromBFibers where
  k := k
  cross_disjoint := cross_disjoint
  fixedPart := centerNeighborPart Γ data.u
  aPart := data.toAFiberCoordinates.allFibers
  parts_disjoint := data.zeroPart_disjoint_toAFiberCoordinates_allFibers
  residual_eq :=
    data.reflectionCopyResidual_toOrbitBaseSelectionInputFromBFibers_eq_zeroPart_union_aFibers
      href
  residual_contribution :=
    data.zeroPart_union_allFibers_residual_contribution boundary

/-- Version of `toComplementResidualSplit38WitnessFromBFibers` with the
mixed B/C disjointness proved from the branch-leaf split. -/
noncomputable def toComplementResidualSplit38WitnessFromBFibersOfReflection
    (data : BranchOrbitABCFromCenter h)
    (boundary :
      AFiberCardinality38Boundary h data.toAFiberCoordinates
        (Finset.univ : Finset (ZMod 19)))
    {k : ZMod 19}
    (href : h.smul (DihedralGroup.sr k) data.b0 = data.c0) :
    AdjacentMovedReflectionComplementResidualSplit38Witness h
      data.toOrbitBaseSelectionInputFromBFibers :=
  data.toComplementResidualSplit38WitnessFromBFibers boundary href
    (data.cross_disjoint_toOrbitBaseSelectionInputFromBFibers_of_reflection_smul_b0_eq_c0
      href)

end BranchOrbitABCFromCenter

end

end Moore57
