import Moore57.D19OnMoore57.BranchOrbit.ABCPartition
import Moore57.D19OnMoore57.BranchOrbit.BCSelection
import Moore57.D19OnMoore57.Misc.CenterNeighborContributionZero
import Moore57.D19OnMoore57.AFiber.CardinalityBoundary
import Moore57.D19OnMoore57.AdjacentMoved.Reflection

/-!
# Section 7 residual split and adjacent-moved contribution

This file unifies two thematic downstream layers of the residual analysis:

* **Residual split** (formerly `ABCResidualSplit`): connects the B/C selected
  base cover to the residual-side partition.  The reflection-copy union is
  the B/C leaf union, so its complement is the center-neighbor zero part
  together with the A-side leaf fibers.
* **Residual contribution** (formerly `ABCResidualContribution`): the
  zero-part contributes zero to the adjacent-moved count, and an
  `AFiberCardinality38Boundary` supplies the `38` contribution from the
  A-side, packaged in the generic compact split-residual witness.

The upstream "Bridge"/"Geometry" layer is in
`BranchOrbit/ResidualBridge.lean`.  `ABCPartition` already imports the bridge
file, so this file sits below `ABCPartition` in the dependency DAG.
-/

namespace Moore57

open Finset

noncomputable section

universe u

variable {V : Type u} [Fintype V] [DecidableEq V]
variable {Γ : SimpleGraph V} [DecidableRel Γ.Adj]

/-! ## Branch-leaf disjointness and zero-part disjointness -/

namespace D19ActsOnMoore57

variable (h : D19ActsOnMoore57 V Γ)

/-- Branch leaves over disjoint center-neighbor rotation orbits are disjoint. -/
theorem branchOrbitLeaf_disjoint_of_rotationOrbitFinset_disjoint
    {u a b : V}
    (hu : ∀ d : ZMod 19, h.rotation d u = u)
    (ha : Γ.Adj u a) (hb : Γ.Adj u b)
    (hdisj : Disjoint (h.rotationOrbitFinset a) (h.rotationOrbitFinset b)) :
    Disjoint (h.branchOrbitLeaf u a) (h.branchOrbitLeaf u b) := by
  rw [Finset.disjoint_left]
  intro y hyA hyB
  rcases (h.mem_branchOrbitLeaf_iff u a y).mp hyA with ⟨i, hyi⟩
  rcases (h.mem_branchOrbitLeaf_iff u b y).mp hyB with ⟨j, hyj⟩
  have hai : Γ.Adj u (h.rotation i a) :=
    h.adj_rotation_of_fixed_center hu ha i
  have hbj : Γ.Adj u (h.rotation j b) :=
    h.adj_rotation_of_fixed_center hu hb j
  have hne : h.rotation i a ≠ h.rotation j b := by
    intro heq
    have hia : h.rotation i a ∈ h.rotationOrbitFinset a :=
      (h.mem_rotationOrbitFinset a (h.rotation i a)).mpr ⟨i, rfl⟩
    have hjb : h.rotation i a ∈ h.rotationOrbitFinset b := by
      rw [heq]
      exact (h.mem_rotationOrbitFinset b (h.rotation j b)).mpr ⟨j, rfl⟩
    exact (Finset.disjoint_left.mp hdisj) hia hjb
  exact (Finset.disjoint_left.mp
    (h.isMoore.branchFiber_disjoint_of_ne hai hbj hne)) hyi hyj

/-- The zero part `{u} ∪ N(u)` is disjoint from every branch leaf over a
center-neighbor rotation orbit. -/
theorem centerNeighborPart_disjoint_branchOrbitLeaf
    {u b : V}
    (hu : ∀ d : ZMod 19, h.rotation d u = u)
    (hb : Γ.Adj u b) :
    Disjoint (centerNeighborPart Γ u) (h.branchOrbitLeaf u b) := by
  rw [Finset.disjoint_left]
  intro y hyZero hyLeaf
  rcases (h.mem_branchOrbitLeaf_iff u b y).mp hyLeaf with ⟨i, hyi⟩
  rcases (mem_centerNeighborPart (Γ := Γ) u y).mp hyZero with hyu | hyAdj
  · exact (mem_branchFiber.mp hyi).1 hyu
  · have hbi : Γ.Adj u (h.rotation i b) :=
      h.adj_rotation_of_fixed_center hu hb i
    exact h.isMoore.no_triangle hbi (mem_branchFiber.mp hyi).2 hyAdj.symm

/-- The rotation orbit of a point in one branch fiber stays inside the branch
leaf generated by the corresponding center-neighbor orbit. -/
theorem rotationOrbitFinset_subset_branchOrbitLeaf_of_mem_branchFiber
    {u b x : V} (hu : ∀ d : ZMod 19, h.rotation d u = u)
    (hx : x ∈ branchFiber Γ u b) :
    h.rotationOrbitFinset x ⊆ h.branchOrbitLeaf u b := by
  intro y hy
  rcases (h.mem_rotationOrbitFinset x y).mp hy with ⟨i, hi⟩
  rw [h.mem_branchOrbitLeaf_iff]
  refine ⟨i, ?_⟩
  rw [← hi]
  exact (h.rotation_mem_branchFiber_iff i
    (u := u) (b := b) (x := x) (hu i)).2 hx

end D19ActsOnMoore57

namespace BranchOrbitABCFromCenter

variable {h : D19ActsOnMoore57 V Γ}

/-! ## Section 7 residual split -/

/-- The zero part is disjoint from the B/C selected leaf union. -/
theorem zeroPart_disjoint_bSideLeaf_union_cSideLeaf
    (data : BranchOrbitABCFromCenter h) :
    Disjoint (centerNeighborPart Γ data.u) (data.bSideLeaf ∪ data.cSideLeaf) := by
  rw [Finset.disjoint_left]
  intro y hyZero hyBC
  rcases Finset.mem_union.mp hyBC with hyB | hyC
  · exact (Finset.disjoint_left.mp
      (h.centerNeighborPart_disjoint_branchOrbitLeaf data.u_fixed data.b0_adj))
      hyZero hyB
  · exact (Finset.disjoint_left.mp
      (h.centerNeighborPart_disjoint_branchOrbitLeaf data.u_fixed data.c0_adj))
      hyZero hyC

/-- The A-side leaf is disjoint from the B-side leaf. -/
theorem aSideLeaf_disjoint_bSideLeaf
    (data : BranchOrbitABCFromCenter h) :
    Disjoint data.aSideLeaf data.bSideLeaf := by
  exact h.branchOrbitLeaf_disjoint_of_rotationOrbitFinset_disjoint
    data.u_fixed data.a0_adj data.b0_adj
    (by simpa using data.pairwise_disjoint 0 1 (by decide))

/-- The A-side leaf is disjoint from the C-side leaf. -/
theorem aSideLeaf_disjoint_cSideLeaf
    (data : BranchOrbitABCFromCenter h) :
    Disjoint data.aSideLeaf data.cSideLeaf := by
  exact h.branchOrbitLeaf_disjoint_of_rotationOrbitFinset_disjoint
    data.u_fixed data.a0_adj data.c0_adj
    (by simpa using data.pairwise_disjoint 0 2 (by decide))

/-- The A-side leaf is disjoint from the B/C selected leaf union. -/
theorem aSideLeaf_disjoint_bSideLeaf_union_cSideLeaf
    (data : BranchOrbitABCFromCenter h) :
    Disjoint data.aSideLeaf (data.bSideLeaf ∪ data.cSideLeaf) := by
  rw [Finset.disjoint_left]
  intro y hyA hyBC
  rcases Finset.mem_union.mp hyBC with hyB | hyC
  · exact (Finset.disjoint_left.mp data.aSideLeaf_disjoint_bSideLeaf) hyA hyB
  · exact (Finset.disjoint_left.mp data.aSideLeaf_disjoint_cSideLeaf) hyA hyC

/-- Complement form of the Section 7 residual split, before substituting a
specific `reflectionCopyUnion`: the complement of the B/C leaf union is the
zero part together with the A-side leaf. -/
theorem compl_bSideLeaf_union_cSideLeaf_eq_zeroPart_union_aSideLeaf
    (data : BranchOrbitABCFromCenter h) :
    (data.bSideLeaf ∪ data.cSideLeaf)ᶜ =
      centerNeighborPart Γ data.u ∪ data.aSideLeaf := by
  ext y
  constructor
  · intro hyCompl
    have hnotBC : y ∉ data.bSideLeaf ∪ data.cSideLeaf := by
      simpa using hyCompl
    rcases mem_centerNeighborPart_or_allBranchFibers h.isMoore data.u y with
      hyZero | hyBranch
    · exact Finset.mem_union.mpr (Or.inl hyZero)
    · have hyABC :
          y ∈ data.aSideLeaf ∪ (data.bSideLeaf ∪ data.cSideLeaf) := by
        simpa [data.allBranchFibers_eq_a_b_c_leaves]
          using hyBranch
      rcases Finset.mem_union.mp hyABC with hyA | hyBC
      · exact Finset.mem_union.mpr (Or.inr hyA)
      · exact False.elim (hnotBC hyBC)
  · intro hy
    have hnotBC : y ∉ data.bSideLeaf ∪ data.cSideLeaf := by
      intro hyBC
      rcases Finset.mem_union.mp hy with hyZero | hyA
      · exact (Finset.disjoint_left.mp
          data.zeroPart_disjoint_bSideLeaf_union_cSideLeaf) hyZero hyBC
      · exact (Finset.disjoint_left.mp
          data.aSideLeaf_disjoint_bSideLeaf_union_cSideLeaf) hyA hyBC
    simpa using hnotBC

/-- Final residual split for a selected base enumerating `L_{b0}`: if the
reflection sends `b0` to `c0`, then the canonical reflection-copy residual is
`zeroPart ∪ A_fiber`. -/
theorem reflectionCopyResidual_b0FiberBase_eq_zeroPart_union_aFibers
    (data : BranchOrbitABCFromCenter h)
    (e : Fin 56 ≃ {x : V // x ∈ branchFiber Γ data.u data.b0})
    {k : ZMod 19}
    (href : h.smul (DihedralGroup.sr k) data.b0 = data.c0) :
    reflectionCopyResidual h (data.b0FiberBase e) k =
      centerNeighborPart Γ data.u ∪ data.toAFiberCoordinates.allFibers := by
  rw [reflectionCopyResidual,
    data.reflectionCopyUnion_b0FiberBase_eq_bSideLeaf_union_cSideLeaf e href,
    data.compl_bSideLeaf_union_cSideLeaf_eq_zeroPart_union_aSideLeaf,
    data.aSideLeaf_eq_allFibers]

/-- Final residual split for the canonical B-fiber selected input.  This is
the Section 7 residual identity in the form consumed by the downstream
`BranchOrbitABCData` bridge. -/
theorem reflectionCopyResidual_toOrbitBaseSelectionInputFromBFibers_eq_zeroPart_union_aFibers
    (data : BranchOrbitABCFromCenter h)
    {k : ZMod 19}
    (href : h.smul (DihedralGroup.sr k) data.b0 = data.c0) :
    reflectionCopyResidual h data.toOrbitBaseSelectionInputFromBFibers.base k =
      centerNeighborPart Γ data.u ∪ data.toAFiberCoordinates.allFibers := by
  rw [data.toOrbitBaseSelectionInputFromBFibers_base_eq_b0FiberBase]
  exact
    data.reflectionCopyResidual_b0FiberBase_eq_zeroPart_union_aFibers
      data.toBFiberCoordinatesBaseFiberEquiv href

/-! ## Adjacent-moved contribution -/

/-- The zero part `{u} ∪ N(u)` is disjoint from the A-side all-fiber union. -/
theorem zeroPart_disjoint_toAFiberCoordinates_allFibers
    (data : BranchOrbitABCFromCenter h) :
    Disjoint (centerNeighborPart Γ data.u) data.toAFiberCoordinates.allFibers := by
  rw [← data.aSideLeaf_eq_allFibers]
  exact h.centerNeighborPart_disjoint_branchOrbitLeaf
    data.u_fixed data.a0_adj

/-- The center-neighbor residual piece plus the A-side all-fiber piece has
constant adjacent-moved contribution `38`. -/
theorem zeroPart_union_allFibers_residual_contribution
    (data : BranchOrbitABCFromCenter h)
    (boundary :
      AFiberCardinality38Boundary h data.toAFiberCoordinates
        (Finset.univ : Finset (ZMod 19))) :
    ∀ d : ZMod 19, ∀ _hd : d ≠ 0,
      ((centerNeighborPart Γ data.u).filter fun y =>
          Γ.Adj y (h.rotation d y)).card +
        (data.toAFiberCoordinates.allFibers.filter fun y =>
          Γ.Adj y (h.rotation d y)).card =
        38 := by
  intro d hd
  have hzero :
      ((centerNeighborPart Γ data.u).filter fun y =>
          Γ.Adj y (h.rotation d y)).card = 0 :=
    h.centerNeighborPart_filter_adjacent_rotation_card_eq_zero
      data.u_fixed d
  have ha :
      (data.toAFiberCoordinates.allFibers.filter fun y =>
          Γ.Adj y (h.rotation d y)).card = 38 := by
    simpa [AFiberCoordinates.allFibers, fixedAFiberAFiberCard] using
      boundary.card_eq_thirtyEight d hd
  simp [hzero, ha]

/-- The B- and C-side branch leaves are disjoint. -/
theorem bSideLeaf_disjoint_cSideLeaf
    (data : BranchOrbitABCFromCenter h) :
    Disjoint data.bSideLeaf data.cSideLeaf := by
  exact h.branchOrbitLeaf_disjoint_of_rotationOrbitFinset_disjoint
    data.u_fixed data.b0_adj data.c0_adj
    (by simpa using data.pairwise_disjoint 1 2 (by decide))

/-- Each canonical B-fiber selected base orbit lies in the B-side leaf. -/
theorem rotationOrbitFinset_toOrbitBaseSelectionInputFromBFibers_base_subset_bSideLeaf
    (data : BranchOrbitABCFromCenter h) (q : Fin 56) :
    h.rotationOrbitFinset (data.toOrbitBaseSelectionInputFromBFibers.base q) ⊆
      data.bSideLeaf := by
  have hmem :
      data.toOrbitBaseSelectionInputFromBFibers.base q ∈
        branchFiber Γ data.u data.b0 := by
    rw [data.toOrbitBaseSelectionInputFromBFibers_base_eq_b0FiberBase]
    exact data.b0FiberBase_mem
      data.toBFiberCoordinatesBaseFiberEquiv q
  exact h.rotationOrbitFinset_subset_branchOrbitLeaf_of_mem_branchFiber
    data.u_fixed hmem

/-- Each reflected canonical B-fiber selected base orbit lies in the C-side
leaf when the reflection sends `b0` to `c0`. -/
theorem rotationOrbitFinset_reflection_toOrbitBaseSelectionInputFromBFibers_base_subset_cSideLeaf
    (data : BranchOrbitABCFromCenter h) {k : ZMod 19}
    (href : h.smul (DihedralGroup.sr k) data.b0 = data.c0)
    (q : Fin 56) :
    h.rotationOrbitFinset
        (h.smul (DihedralGroup.sr k)
          (data.toOrbitBaseSelectionInputFromBFibers.base q)) ⊆
      data.cSideLeaf := by
  have hmem :
      h.smul (DihedralGroup.sr k)
          (data.toOrbitBaseSelectionInputFromBFibers.base q) ∈
        branchFiber Γ data.u data.c0 := by
    rw [data.toOrbitBaseSelectionInputFromBFibers_base_eq_b0FiberBase]
    exact data.reflection_b0FiberBase_mem_c0Fiber
      data.toBFiberCoordinatesBaseFiberEquiv href q
  exact h.rotationOrbitFinset_subset_branchOrbitLeaf_of_mem_branchFiber
    data.u_fixed hmem

/-- Original B-fiber selected orbits and their reflected C-side copies are
pairwise disjoint. -/
theorem cross_disjoint_toOrbitBaseSelectionInputFromBFibers_of_reflection_smul_b0_eq_c0
    (data : BranchOrbitABCFromCenter h) {k : ZMod 19}
    (href : h.smul (DihedralGroup.sr k) data.b0 = data.c0) :
    ∀ q r : Fin 56,
      Disjoint
        (h.rotationOrbitFinset
          (data.toOrbitBaseSelectionInputFromBFibers.base q))
        (h.rotationOrbitFinset
          (h.smul (DihedralGroup.sr k)
            (data.toOrbitBaseSelectionInputFromBFibers.base r))) := by
  intro q r
  rw [Finset.disjoint_left]
  intro y hyB hyC
  exact (Finset.disjoint_left.mp data.bSideLeaf_disjoint_cSideLeaf)
    (data.rotationOrbitFinset_toOrbitBaseSelectionInputFromBFibers_base_subset_bSideLeaf
      q hyB)
    (data.rotationOrbitFinset_reflection_toOrbitBaseSelectionInputFromBFibers_base_subset_cSideLeaf
      href r hyC)

/-- Package the natural-language Section 7 residual split as the generic
compact split-residual witness for the canonical B-fiber selected input. -/
noncomputable def toComplementResidualSplit38WitnessFromBFibers
    (data : BranchOrbitABCFromCenter h)
    (boundary :
      AFiberCardinality38Boundary h data.toAFiberCoordinates
        (Finset.univ : Finset (ZMod 19)))
    {k : ZMod 19}
    (href : h.smul (DihedralGroup.sr k) data.b0 = data.c0)
    (cross_disjoint :
      ∀ q r : Fin 56,
        Disjoint
          (h.rotationOrbitFinset
            (data.toOrbitBaseSelectionInputFromBFibers.base q))
          (h.rotationOrbitFinset
            (h.smul (DihedralGroup.sr k)
              (data.toOrbitBaseSelectionInputFromBFibers.base r)))) :
    AdjacentMovedReflectionComplementResidualSplit38Witness h
      data.toOrbitBaseSelectionInputFromBFibers where
  k := k
  cross_disjoint := cross_disjoint
  fixedPart := centerNeighborPart Γ data.u
  aPart := data.toAFiberCoordinates.allFibers
  parts_disjoint := data.zeroPart_disjoint_toAFiberCoordinates_allFibers
  residual_eq :=
    data.reflectionCopyResidual_toOrbitBaseSelectionInputFromBFibers_eq_zeroPart_union_aFibers
      href
  residual_contribution :=
    data.zeroPart_union_allFibers_residual_contribution boundary

/-- Version of `toComplementResidualSplit38WitnessFromBFibers` with the
mixed B/C disjointness proved from the branch-leaf split. -/
noncomputable def toComplementResidualSplit38WitnessFromBFibersOfReflection
    (data : BranchOrbitABCFromCenter h)
    (boundary :
      AFiberCardinality38Boundary h data.toAFiberCoordinates
        (Finset.univ : Finset (ZMod 19)))
    {k : ZMod 19}
    (href : h.smul (DihedralGroup.sr k) data.b0 = data.c0) :
    AdjacentMovedReflectionComplementResidualSplit38Witness h
      data.toOrbitBaseSelectionInputFromBFibers :=
  data.toComplementResidualSplit38WitnessFromBFibers boundary href
    (data.cross_disjoint_toOrbitBaseSelectionInputFromBFibers_of_reflection_smul_b0_eq_c0
      href)

end BranchOrbitABCFromCenter

end

end Moore57
